# Permalinks
permalink:        "/blog/:title"
relative_permalinks: true

# Setup
title:            Burger
tagline:
url:              "http://mblode.github.io/burger"
baseurl:          "/burger/"
paginate:         3
author:
  name:           Matthew Blode
  url:            https://twitter.com/mblode
  email:          m.blode@gmail.com

# Custom vars
version:          1.2.2
github:
  repo:           https://github.com/mblode/burger

highlighter: pygments
safe: true
lsi: false

sass:
  style: :compressed

exclude: ["node_modules", "gulpfile.js", "package.json", "bower-components", "bower.json"]
