# Site settings
title: Burger
email: m.blode@gmail.com
description: Burger - The minimal hamburger menu with fullscreen navigation.
baseurl: "/burger" # the subpath of your site, e.g. /blog/
url: "http://mblode.github.io" # the base hostname & protocol for your site
twitter_username: mblode
github_username:  mblode

# Build settings
markdown: kramdown
exclude: [node_modules]
